import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Logout from "./logout";
import Header from './components/header/header';
import Menu from './components/menu/menu';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
    <body className={inter.className}>
      {session ? (
        <>
          <Header />
          <div style={{ display: 'flex' }}>
            <Menu />
            <main style={{ flex: 1 }}>{children}</main>
            <Logout />
          </div>
        </>
      ) : (
        children
      )}
    </body>
  </html>
  );
}
